version: 2.1

orbs:
  snyk: snyk/snyk@1.7.0

jobs:
  install:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - run: npm ci
      - snyk/scan

workflows:
  build-and-deploy:
    jobs:
      - install:
          context: snyk-security