version: 2.1

orbs:
  slack: circleci/slack@4.12.5

notify_slack: &notify_slack
  - slack/notify:
      event: pass
      template: success_tagged_deploy_1
      mentions: '@slack-username'

jobs:
  hello-world:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - run: npx cowsay "Hello"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - hello-world:
          filters:
            branches:
              only: main
          <<: *notify_slack
