version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  hello-world:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - run: npx cowsay "Hello"
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          mentions: '@slack-username'

workflows:
  build-and-deploy:
    jobs:
      - hello-world:
          filters:
            branches:
              only: main
